# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

source $HOME/antigen.zsh
antigen init $HOME/.antigenrc

POWERLEVEL9K_MODE="nerdfont-complete"

# Theme is set via `antibody`, see `config/antibody.txt`.
# ZSH_THEME="sobole"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="false"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="false"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"
HIST_IGNORE_SPACE="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(
  git
  gitfast
  python
  django
  osx
  brew
  extract
#  hacker-quotes
#  fasd
  kubectl
  gitignore
)

# User configuration

export PATH="/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/opt/php56/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

# Custom envs:
#if type brew &>/dev/null; then
#  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
#fi

source $ZSH/oh-my-zsh.sh
source $HOME/.shell_env

# You may seed to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# The following lines were added by compinstall

#zstyle ':completion:*' completer _complete _ignored _correct _approximate
#zstyle ':completion:*' max-errors 3
#zstyle ':completion:*' prompt '1'
#zstyle :compinstall filename '$HOME/.zshrc'

#autoload -Uz compinit
#compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
#bindkey -e
# End of lines configured by zsh-newuser-install
#if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi
#if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi
#if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi

#source $HOME/antigen.zsh 
